add setOuterHtml for HtmlNode
thesoftwarefanatics/php-html-parser pull request #14
Opened 2018-08-26 09:14 UTC by gfd6th

2018-08-26 10:10 UTC, plonknimbuzz commented
why we need to set outerHtml?

2018-08-26 10:15 UTC, gfd6th commented
Maybe we need replace node sometimes, when our content from user submit
eg: 
```php

$node = '<span data-link='http://foo.com'>foo.com</span>';

$dom->load($node);
$dom->setOuterHtml('<a href="http://foo.com">foo.com</a>');

$model->body = (string) $dom;
$model->save();

```

2018-08-27 05:17 UTC, alcaeus requested changes
Thanks for your contribution. Please add tests for your changes and fix review issues.

2018-08-27 05:17 UTC, alcaeus commented on composer.json
> +    "name": "gfd6th/php-html-parser",
This needs to be removed, can't merge the pull request with it.

2018-08-28 16:58 UTC, plonknimbuzz commented
i see. i think this will be great for the future.
i ask that question, because i never need/use that method.  but maybe someday this feature will help me alot.
thanks for the explaination, very usefull for me.

2018-12-21 07:34 UTC, alcaeus commented
After taking another look at the functionality, we will not be merging this. The outerHtml property is generated and should thus be considered immutable. Changing the outerHtml of a node should happen by creating a new node and adding all children from the original node. Thank you for your contribution.

2018-12-21 07:34 UTC, closed without merging